1、toast控件识别
    什么是toast：登录页面输入账号和密码，点击登录按钮，页面提示“登录成功”一闪而过，不需要用户进行任何操作，只是一个提示
2、toast定位
    appium使用uiautomator底层的机制来分析抓取toast，并且把toast放到控件里面，但本身并不属于控件
	automationName：uiautomator2
	getPageSource是无法找到的
	必须使用xpath查找
	//*[@class='android.widget.Toast']
	//*[contains(@text,"xxxxx")]
3、toast介绍
    Toast,简易的消息提示框
	为了给当前师徒显示一个浮动的显示块，与dialog不同，它永远不会获得焦点
	Toast类的思想：尽可能不引人注意，同时还向用户显示信息希望它们看到
	Toast显示的时间有限，Toast会根据用户设置的显示时间后自动消失
	Toast本身是个系统级别的控件，它归属于系统settings，当一个app发送消息的时候，不是自己造出来的这个弹框，
	它是发给系统，由系统统一进行弹框，这类的控件不在app内，
    需要特殊的控件识别方法